config/routes.rb
H3::Application.routes.draw do

  get "console/index"
  get "console/graphs"
  get "console/readings"
  get "console/documentation"
  get "console/anomalies"    => 'console#readings', :type => 'anomalies'
  get "console/failures"     => 'console#readings', :type => 'failures'
  get 'console/log/:guid'  => 'console#log'
   
  get "home/index"

  get 'sensor/gauge/:source' => 'sensors#gauge'
  get 'sensor/meter/:source' => 'sensors#meter'

  put 'switch/set/:source/:state'   => 'switch#set_switch'

  root :to => "home#index"

  resources :sessions
  resources :users
  
  resources :alarm, :only => :create

  get '/api/:data_store/sources'                    => 'api#get_sensor_list', :defaults => { :format => 'json' }  # list sources
  get '/api/:data_store/readings'                   => 'api#get_readings',    :defaults => { :format => 'json' }  # show the most recent reading / state for each source
  get '/api/:data_store/messages'                   => 'api#get_messages',    :defaults => { :format => 'json' }  # get most recent messages (eg "alarm activated")
  get '/api/:data_store/may_switch/:switch'         => 'api#may_switch?'                                           # return 200 if its not going to rain, 418 if it is
  get '/api/:data_store/:source/reading'            => 'api#get_readings',    :defaults => { :format => 'json' }  # for a single sensor, show the current state
  get '/api/:data_store/:source/readings'           => 'api#get_history',     :defaults => { :format => 'json' }  # show the most recent readings (50) for a sensor
  get '/api/:data_store/:source/:dimension'         => 'api#get_summaries',   :defaults => { :format => 'json' }  # retrieve the last 50 summarised data points for a sensor, for a dimension
  get '/api/:data_store/:source/:dimension/summary' => 'api#get_summary',     :defaults => { :format => 'json' }  # get the most recent summary value for a sensor, for a dimension
  get '/api/:data_store/:dimension'                 => 'api#get_summaries',   :defaults => { :format => 'json' }  # for a dimension, retrieve all the summarised values for all sensors
  put '/api/:data_store/:source/:value'             => 'api#udp_put'                                              # push a message to the UDP server

  get 'login'   => 'sessions#new'
  get 'logout'  => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>H3</title>
  < % = stylesheet_link_tag    "application" % >
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 60px; padding-bottom: 40px;">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "The Watermeyers!", root_path, :class => 'brand' %>

          <div class="nav-collapse">
            <ul class="nav">

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Analysis <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Temperature', console_index_path %></li>
                  <li><%= link_to 'Electricity', console_index_path %></li>
                  <li><%= link_to 'Bandwidth', console_index_path %></li>
                </ul>
              </li>

             <li class="dropdown active">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Switches <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Alarm', console_index_path %></li>
                </ul>
              </li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gauges <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <% sources.each do |key, value| %>
                    <% if value[:monitor_type]==:gauge  %>
                      <li><%= link_to value[:name], "/sensor/gauge/#{key}" %></li> 
                    <% end %>
                  <% end  %>
                </ul>
              </li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Meters <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <% sources.each do |key, value| %>
                    <% if value[:monitor_type]==:pulse %>
                      <li><%= link_to value[:name], "/sensor/meter/#{key}" %></li>
                    <% end %>
                  <% end  %>
                </ul>
              </li>
            </ul>
            <ul class="nav pull-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Console <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Current Readings", console_index_path %></li>
                  <li><%= link_to "Graphs", console_graphs_path %></li>
                  <li><%= link_to "Readings Log", console_readings_path(:n=>"50") %></li>
                  <li><a href="/console/anomalies?n=50">Anomalies</a></li>
                  <li><a href="/console/failures?n=50">Failures</a></li>
                  <li class="divider"></li>
                  <li><%= link_to "1Wire", "http://192.168.0.252:2121/" %></li>
                  <li><%= link_to "Rabbit", "http://192.168.0.252:15672/#/" %></li>
                  <li class="divider"></li>
                  <li><%= link_to "API Documentation", console_documentation_path %></li>
                </ul>
              </li>
            </ul>

          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" style="display: none" id="flash">
      <div class="alert alert-error" id="flash_message">
        <strong>Error!</strong> The connection to server has failed.
      </div>
    </div>

    <div class="container">
<%= yield %>
      <hr>

      <footer>
        <p>&copy; The Watermeyers, 2012</p>
      </footer>

  </div>

</body>

<script type="text/javascript">
  <%= yield :js_end %>

  $(function() {
    <%= yield :js_init %>
  });

  FieldFormatter.format_fields();

</script>

</html>